'use strict';
// @nossen/all-in-one - one import for the whole NOSSEN / Funesterie AI toolkit.
function t(name){ try { return require(name); } catch(e){ return { __requireError: name+': '+e.message }; } }
module.exports = {
  allmight: t('@nossen/allmight'),
  bat: t('@nossen/bat'),
  bat_system: t('@nossen/bat-system'),
  beam: t('@nossen/beam'),
  dragon: t('@nossen/dragon'),
  dragon_contracts: t('@nossen/dragon-contracts'),
  dragon_upstream: t('@nossen/dragon-upstream'),
  envapt_superimg: t('@nossen/envapt-superimg'),
  envaptex: t('@nossen/envaptex'),
  freeland: t('@nossen/freeland'),
  freeland_bros: t('@nossen/freeland-bros'),
  katana: t('@nossen/katana'),
  knowledge_modules: t('@nossen/knowledge-modules'),
  logic_reduce: t('@nossen/logic-reduce'),
  mcp_agent_bus: t('@nossen/mcp-agent-bus'),
  mcp_chopper_mixer: t('@nossen/mcp-chopper-mixer'),
  mcp_cloud_assets: t('@nossen/mcp-cloud-assets'),
  mcp_job_queue: t('@nossen/mcp-job-queue'),
  mcp_media_bridge: t('@nossen/mcp-media-bridge'),
  mcp_memory_graph: t('@nossen/mcp-memory-graph'),
  mcp_public_endpoints: t('@nossen/mcp-public-endpoints'),
  mcp_qflush_control: t('@nossen/mcp-qflush-control'),
  mcp_retro_session: t('@nossen/mcp-retro-session'),
  mcp_security_preflight: t('@nossen/mcp-security-preflight'),
  mcp_tool_manifest: t('@nossen/mcp-tool-manifest'),
  mcp_toolkit: t('@nossen/mcp-toolkit'),
  mcp_web_drafts: t('@nossen/mcp-web-drafts'),
  mcp_worker_supervisor: t('@nossen/mcp-worker-supervisor'),
  morphing: t('@nossen/morphing'),
  nezlephant: t('@nossen/nezlephant'),
  qflush: t('@nossen/qflush'),
  qflush_runner: t('@nossen/qflush-runner'),
  rome: t('@nossen/rome'),
  scentgate: t('@nossen/scentgate'),
  scream: t('@nossen/scream'),
  spyder: t('@nossen/spyder'),
  zen: t('@nossen/zen'),
  cf: t('@nossen/cf'),
  hetzner: t('@nossen/hetzner'),
  zen_gate: t('@nossen/zen-gate'),
};
